name: Duel
version: 1.1.3M
description: >
  Challenge other players to a duel!

author: TfT_02, Melonking
website: http://dev.bukkit.org/server-mods/duel/

main: com.me.tft_02.duel.Duel
softdepend: [WorldGuard]

commands:
   duel:
      description: Usage /duel
      permission-message: You don't have <permission>
permissions:
    duel.challenge:
        description: Users with this permission are allowed to challenge other players to a duel.
        default: true
    duel.updatecheck:
        description: Users with this permission will receive a notification when there is a new version available.
        default: op
